# Generated by Django 2.1.4 on 2018-12-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbrite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
